config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # SYNTAX = verb path, to: controller#controller_action

  # READ all tasks
  get '/tasks', to: 'tasks#index' # we can have any path we want pointing to any controller action
  # READ 1 task
  get '/tasks/new', to: 'tasks#new' # display a new empty form for a new task (belongs to CREATE)
  get '/tasks/:id', to: 'tasks#show', as: :task# reading an exisiting task by id
  # CREATE 1 task
  post '/tasks', to: 'tasks#create' # creates task upon clicking submit (its a convention from the form which always posts to index)
  # UPDATE 1 task
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task # edit page for prefilled form for a specific task ID
  patch '/tasks/:id', to: 'tasks#update'
  # DELETE 1 task
  delete '/tasks/:id', to: 'tasks#destroy', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to task_path(task) # there is no view so I need to forward to showpage of that task (task_path = route to show; task = instance)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task.update(task_params)

    redirect_to task_path(@task) # Redirect to the show page
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  # STRONG PARAMS:
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container">

<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :completed %>
  <%= f.submit %>
<% end %>

</div>

app/views/tasks/destroy.html.erb
<h1>Hello destroy</h1>

app/views/tasks/edit.html.erb
<h1>Edit your task here...</h1>
<%= render 'form' %>

<%= link_to 'Back to list', tasks_path(@tasks)  %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul>
  <% @tasks.each do |task| %>
  <li>  <%= link_to task.title, task_path(task) %></li>
  <% end %>
</ul>


<%= link_to 'Add a new task', tasks_new_path(@tasks)  %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= render 'form' %>

<%= link_to 'Back to list', tasks_path(@tasks)  %>

app/views/tasks/show.html.erb
<h1><%= @task.title %> </h1>
<h2><%= @task.details %></h2>
<h2><%= @task.completed %></h2>

<%= link_to 'Back to list', tasks_path(@tasks)  %>
<%= link_to 'Edit this task', edit_task_path(@task)  %>
<%= link_to 'Delete this task', delete_path(@task), method: :delete, data: {confirm: 'Are you sure you want to delete?'} %>

app/views/tasks/update.html.erb
<h1>Hello update</h1>


<%= link_to 'Back to list', tasks_path(@tasks)  %>